spring:
  application:
    name: api-pdc
  datasource:
    url: jdbc:mysql://localhost:3306/d42-api-pdc
    username: apiUser
    password: late%37

server:
  port: 4200
  servlet:
    context-path: /api-pdc
  shutdown: graceful

logging:
  file:
    name: logs/trace.log