spring:
  application:
    name: api-pdc
  datasource:
    url: jdbc:mysql://localhost:3306/restapi
    username: root
    password: Pedrosousa@123

server:
  port: 8080
  servlet:
    context-path: /api-pdc
  shutdown: graceful

logging:
  file:
    name: logs/trace.log